
mappings = {

    "trialDescriptions.tptIdKey":"TD key",
    "trialDescriptions.crops.name":"Crop",
    "trialDescriptions.trialResponsibles.internalValue":"INT EXT",
    "trialDescriptions.trialResponsibles.testType":"Test Type",
    "trialDescriptions.projectNumbers":"Project Number",
    "trialDescriptions.trialResponsibles.siteName":"Site Code",
    "trialDescriptions.siteType":"Site Type",
    "trialDescriptions.plannedNumberOfApplications":"Planned No. of Appl.",
    "trialDescriptions.numberOfReplicates":"Number of replicates / Plot Area",
    "trialDescriptions.trialResponsibles.hasName":"Responsible",
    "trialDescriptions.trialResponsibles.plannedNumberOfTrials":"No. Of trials",
    "trialDescriptions.experimentalSeason":"Experimental season",
    "trialDescriptions.targets.name":"Target",
    "trialDescriptions.plannedAssessments": 0, 
    "trialDescriptions.plannedAssessments.partRated": "Assessment table/Part rated",
    "trialDescriptions.plannedAssessments.ratingDataType": "Assessment table/Assessment type",
    "trialDescriptions.plannedAssessments.sampleSize": "Assessment table/Sample size",
    "trialDescriptions.plannedAssessments.sampleSizeUnit": "Assessment table/Sample size unit",
    "trialDescriptions.plannedAssessments.target": 5,
    "trialDescriptions.plannedAssessments.target.name": "Assessment table/Target",
    "trialDescriptions.plannedAssessments.crop": 5, 
    "trialDescriptions.plannedAssessments.crop.name": "Assessment table/Crop", 
    "trialDescriptions.plannedAssessments.assessmentCode": "Assessment table/Assessment code",
    "trialDescriptions.plannedAssessments.standardEvaluationId": "Assessment table/Standard Evaluation (SE)",
    "trialDescriptions.treatments.applications": "Protocol description/Application timing",
    "trialDescriptions.treatments.applications.applicationTiming": "Protocol description/Application timing",
    "trialDescriptions.treatments.applications.products.equipment.method": "Protocol description/Application Method",
    "trialDescriptions.treatments.applications.products.equipment.placement": "Protocol description/Application Placement",             
    "trialDescriptions.treatments.applications.crops": "Assessment table/Crop",
    "trialDescriptions.treatments.applications.targets": "Assessment table/Target",
    "trialDescriptions.treatments.applications.crops.cropStageCode": "Crop stage /App./Majority",
    "trialDescriptions.keywords": "Objective",
    "trialDescriptions.gepCode": "GEP level",
    "trialDescriptions.gepCertification":"GEP certificate link",
    "trialDescriptions.guidelines": "Guidelines",
    "trialDescriptions.plannedNumberOfApplications": "Planned No. of Appl.",
    "trialDescriptions.plannedNumberOfAssessments": "No. of Assessments/Trial",
    "trialDescriptions.controlFieldCode":"Location of control",
    "trialDescriptions.dataDeadline":"Data deadline",
    "trialDescriptions.treatments.applications.applicationCode":"Application code"
}