{
    "fieldtrials.status":"Trial Status",
    "fieldtrials.quality":"Trial Quality",
    "fieldtrials.objectivesFulfilled":"Trial Objectives Fulfilled",
    "fieldtrials.externalTrialNumber":"External Trial No.",
    "fieldtrials.location":"City",
    "fieldtrials.location.city":"City",
    "fieldtrials.location.zip":"Postal Code",
    "fieldtrials.location.country":"Country",
    "fieldtrials.location.latitude":"Latitude",
    "fieldtrials.location.longitude":"Longitude",
    "fieldtrials.tillageType":"Tillage Type",
    "fieldtrials.closestWeatherStation":"Most relevant weather station",
    "fieldtrials.soil":"Texture",
    "fieldtrials.soil.texture":"Texture",
    "fieldtrials.soil.percentSilt":"% Silt",
    "fieldtrials.soil.percentClay":"% Clay",
    "fieldtrials.soil.percentSand":"% Sand",
    "fieldtrials.soil.percentOrganicMatter":"% Organic Matter",
    "fieldtrials.soil.pH":"pH",
    "fieldtrials.irrigations.date":"Date irrigation",
    "fieldtrials.irrigations.amount":"Amount",
    "fieldtrials.irrigations.amountUnit":"Unit",
    "fieldtrials.irrigations.equipmentType":"Type and Equipment",
    "fieldtrials.crops":"Crop",
    "fieldtrials.crops.name":"Crop",
    "fieldtrials.crops.variety":"Variety",
    "fieldtrials.crops.planting.date":"Seed/Planting Date",
    "fieldtrials.crops.planting.rate":"Seed/Plant Rate",
    "fieldtrials.crops.planting.rateUnit":"Seed/Plant Rate Unit",
    "fieldtrials.crops.planting.transplantingDate":"Date of Tranplanting",
    "fieldtrials.crops.planting.seedCount":"Seed Plant Count",
    "fieldtrials.crops.planting.seedCountUnit":"Seed Plant Count Unit",
    "fieldtrials.crops.planting.depth":"Depth",
    "fieldtrials.crops.planting.depthUnit":"Depth Unit",
    "fieldtrials.crops.planting.rowSpacing":"Row Spacing",
    "fieldtrials.crops.planting.rowSpacingUnit":"Row Spacing Unit",
    "fieldtrials.crops.planting.spacingWithinRow":"Spacing within Row",
    "fieldtrials.crops.planting.spacingWithinRowUnit":"Spacing within Row Unit",
    "fieldtrials.crops.planting.rowsPerPlot":"Rows per Plot",
    "fieldtrials.crops.planting.method":"Planting Method",
    "fieldtrials.crops.planting.implement":"Planting Implement",
    "fieldtrials.crops.planting.soilMoisture":"Soil Moisture (at Planting)",
    "fieldtrials.crops.planting.cropStage":"Planting Crop Stage",
    "fieldtrials.crops.perennialAge":"Perennial Age",
    "fieldtrials.crops.perennialAgeUnit":"Perennial Age Unit",
    "fieldtrials.targets":"Target",
    "fieldtrials.targets.name":"Target",
    "fieldtrials.targets.resistances.description":"Resistance Characteristics",
    "fieldtrials.targets.resistanceInformation":"Resistance Information",

    


    "fieldtrials.treatments":"Application Code", 
    "fieldtrials.treatments.applications":"Application Code", 
    "fieldtrials.treatments.applications.applicationCode":"Application Code", 
    "fieldtrials.treatments.applications.date":"Application Date",
    "fieldtrials.treatments.applications.applicationTiming":"Appl. Start - Time of day",
    "fieldtrials.treatments.applications.percentRelativeHumidity":"% Relative Humidity",
    "fieldtrials.treatments.applications.airTemperature":"Air temperature",
    "fieldtrials.treatments.applications.airTemperatureUnit":"Air temperature Unit",
    "fieldtrials.treatments.applications.percentCloudCover":"% Cloud Cover",
    "fieldtrials.treatments.applications.windStrength":"Appl. Wind Strength",
    "fieldtrials.treatments.applications.crops.plantingCondition":"Plant Condition",
    "fieldtrials.treatments.applications.soilMoisture":"Soil Moisture",
    "fieldtrials.treatments.applications.soilCondition":"Soil Condition (surface)",
    "fieldtrials.treatments.applications.products.equipment.problem":"Problem with Application?",

    "fieldtrials.treatments.applications.crops":"Crop Coverage (%)",
    "fieldtrials.treatments.applications.crops.percentageCropCoverage":"Crop Coverage (%)",
    "fieldtrials.treatments.applications.plantCondition":"Application Plant Condition",
    "fieldtrials.treatments.applications.crops.cropStage":"Crop Stage Majority (appl)",
    "fieldtrials.treatments.applications.crops.percentageAtCropStage":"Crop Stage Majority Percent (appl)",
    "fieldtrials.treatments.applications.crops.minCropStage":"Crop Stage Minimum (appl)",
    "fieldtrials.treatments.applications.crops.percentageAtMinCropStage":"Crop Stage Minimum Percent (appl)",
    "fieldtrials.treatments.applications.crops.maxCropStage":"Crop Stage Maximum (appl)",
    "fieldtrials.treatments.applications.crops.percentageAtMaxCropStage":"Crop Stage Maximum Percent (appl)",
    "fieldtrials.treatments.applications.targets":"Target Stage Majority (appl)",
    "fieldtrials.treatments.applications.targets.targetStage":"Target Stage Majority (appl)",
    "fieldtrials.treatments.applications.targets.percentageAtTargetStage":"Target Stage Majority Percent (appl)",
    "fieldtrials.treatments.applications.targets.minTargetStage":"Target Stage Minimum (appl)",
    "fieldtrials.treatments.applications.targets.percentageAtMinTargetStage":"Target Stage Minimum Percent (appl)",
    "fieldtrials.treatments.applications.targets.maxTargetStage":"Target Stage Maximum (appl)",
    "fieldtrials.treatments.applications.targets.percentageAtMaxTargetStage":"Target Stage Maximum Percent (appl)",
    "fieldtrials.treatments.applications.targets.density":"Density",
    "fieldtrials.treatments.applications.targets.densityUnit":"Density Unit",
    "fieldtrials.treatments.applications.targets.coverage":"Coverage",
    "fieldtrials.treatments.applications.targets.coverageUnit":"Coverage Unit",

    "fieldtrials.treatments.applications.products":"Application Method",
    "fieldtrials.treatments.applications.products.equipment.method":"Application Method",
    "fieldtrials.treatments.applications.products.equipment.placement":"Application Placement",
    "fieldtrials.treatments.applications.products.equipment.equipmentType":"Application Equipment",
    "fieldtrials.treatments.applications.products.equipment.propellantType":"Propellant Type",
    "fieldtrials.treatments.applications.products.equipment.diluentCarrier":"Carrier",
    "fieldtrials.treatments.applications.products.equipment.sprayVolume":"Appl./Slurry Volume",
    "fieldtrials.treatments.applications.products.equipment.sprayVolumeUnit":"Appl./Slurry Volume Unit",
    "fieldtrials.treatments.applications.products.equipment.operatingPressure":"Operating Pressure",
    "fieldtrials.treatments.applications.products.equipment.operatingPressureUnit":"Operating Pressure Unit",
    "fieldtrials.treatments.applications.products.equipment.nozzleType":"Nozzle Type",
    "fieldtrials.treatments.applications.products.equipment.nozzleSize":"Nozzle Size",
    "fieldtrials.treatments.applications.products.equipment.nozzleSpacing":"Nozzle Spacing",
    "fieldtrials.treatments.applications.products.equipment.nozzleSpacingUnit":"Nozzle Spacing Unit",
    "fieldtrials.treatments.applications.products.equipment.bandWith":"Band Width",
    "fieldtrials.treatments.applications.products.equipment.bandWithUnit":"Band Width Unit",
    "fieldtrials.treatments.applications.products.equipment.boomHeight":"Boom Height",
    "fieldtrials.treatments.applications.products.equipment.boomHeightUnit":"Boom Height Unit",
    "fieldtrials.treatments.applications.products.equipment.incorporation":"Incorporation Flag",
    "fieldtrials.treatments.applications.products.equipment.incorporationEquipment":"Incorporation Equipment",
    "fieldtrials.treatments.applications.products.equipment.incorporationDepth":"Incorporation Depth",
    "fieldtrials.treatments.applications.products.equipment.incorporationDepthUnit":"Incorporation Depth Unit",

    "fieldtrials.sideActivities.date":"Date",
    "fieldtrials.sideActivities.dosage":"Dosage",
    "fieldtrials.sideActivities.dosageUnit":"Dosage Unit",
    "fieldtrials.sideActivities.description":"Maintenance Product Name",







    "fieldtrials.treatments.assessmentMeanValues":"SE ID",
    "fieldtrials.treatments.assessmentMeanValues.standardEvaluationId":"SE ID",
    "fieldtrials.treatments.assessmentMeanValues.label":"SE Label",
    "fieldtrials.treatments.assessmentMeanValues.target.name":"Target assessment",

    "fieldtrials.treatments.assessmentMeanValues.target":"Target assessment",
    "fieldtrials.treatments.assessmentMeanValues.targetStage":"Stage Majority target",
    "fieldtrials.treatments.assessmentMeanValues.minTargetStage":"Stage Minimum target",
    "fieldtrials.treatments.assessmentMeanValues.maxTargetStage":"Stage Maximum target",

    "fieldtrials.treatments.assessmentMeanValues.cropStage":"Stage Majority crop",
    "fieldtrials.treatments.assessmentMeanValues.minCropStage":"Stage Minimum crop",
    "fieldtrials.treatments.assessmentMeanValues.maxCropStage":"Stage Maximum crop",



    "fieldtrials.treatments.assessmentMeanValues.partRated":"Part Rated",
    "fieldtrials.treatments.assessmentMeanValues.ratingClass":"Ass. Class",
    "fieldtrials.treatments.assessmentMeanValues.ratingType":"Assessment Type",
    "fieldtrials.treatments.assessmentMeanValues.unit":"Assessment Unit",
    "fieldtrials.treatments.assessmentMeanValues.sampleSize":"Sample Size",
    "fieldtrials.treatments.assessmentMeanValues.sampleSizeUnit":"Sample Size Unit",
    "fieldtrials.treatments.assessmentMeanValues.date":"Assessment Date",
    "fieldtrials.treatments.assessmentMeanValues.assessmentCode":"Assessment Code",

    "fieldtrials.gepCode": "GEP",
    "fieldtrials.trialDesign":"Randomization"


}